[versions]

java = "26"

# main
# https://github.com/jspecify/jspecify/releases
jspecify = "1.0.1"
# https://mvnrepository.com/artifact/org.antlr/antlr4
antlr4 = "4.13.2"

# test + test fixtures
# https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api
junit = "6.1.3"
# https://mvnrepository.com/artifact/org.assertj/assertj-core
assertj = "3.27.7"
# https://mvnrepository.com/artifact/org.slf4j/slf4j-jdk-platform-logging
slf4j = "2.0.18"
# https://mvnrepository.com/artifact/ch.qos.logback/logback-classic
logback = "1.6.3"
